version: "3.8"

services:
  database:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=crud
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
  fizzbuzz:
    container_name: fizzbuzz
    build: .
    image: fizzbuzz
    ports:
      - 8080:8080
    environment:
      APP_PORT: 8080
      DB_HOST: database
      DB_USER: pg
      DB_PASSWORD: pass
      DB_PORT: 5432
      DB_NAME: crud
    depends_on:
      - database
volumes:
  database: