version: "3.8"

services:
  database:
    container_name: fizzbuzz
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=crud
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data     
volumes:
  db: